Add steps
Se agregan mas pasos en la automatizacion

diff --git a/.github/workflows/azure-static-web-apps-nice-hill-06f5ec50f.yml b/.github/workflows/azure-static-web-apps-nice-hill-06f5ec50f.yml
--- a/.github/workflows/azure-static-web-apps-nice-hill-06f5ec50f.yml
+++ b/.github/workflows/azure-static-web-apps-nice-hill-06f5ec50f.yml
@@ -23,6 +23,23 @@ jobs:
         with:
           submodules: true
           lfs: false
+
+      - name: Set up Node.js
+        uses: actions/setup-node@v2
+        with:
+          node-version: 20
+
+      - name: Install dependencies
+        run: npm install
+        working-directory: Front-end
+      
+      - name: Build Angular App
+        run: npm run build -- --output-path=dist/test
+        working-directory: Front-end
+
+      - name: List build output
+        run: ls -la Front-end/dist/test || echo "Output directory not found"  
+      
       - name: Build And Deploy
         id: builddeploy
         uses: Azure/static-web-apps-deploy@v1
